In [1]:
import pandas as pd

In [3]:
pd.read_parquet('/wolke_scratch/dnikolo/ICON_Data/Postproc_out/Results/R_Agg_30_clouds_20080901.0015_20080907.2345.parquet')

,tracknumber,is_large_pix_cloud,is_cot_valid_cloud,is_ctp_valid_cloud,is_liq,is_mix,is_ice,max_water_frac,max_ice_fraction,avg_size[km],...,ctt_hist,ctt_std_hist,lat_hist,lon_hist,size_hist_km,min_temp,max_temp,pole,Hemisphere,Lifetime [h]
0,1,False,False,False,True,True,False,1.000000,0.303952,194.715596,...,[],[],"[-48.57432432432432, -48.651162790697676, -48....","[91.15878378378379, 91.0282392026578, 90.62871...","[296.0, 301.0, 303.0, 302.0, 303.0, 303.0, 301...",-6,0,np,North,108.75
1,2,False,False,False,True,True,False,0.997259,0.396851,99.828947,...,[],[],"[-58.38532110091743, -58.5, -59.00724637681159...","[-93.3256880733945, -94.15131578947368, -93.21...","[218.0, 228.0, 207.0, 208.0, 216.0, 218.0, 201...",-6,0,np,North,56.75
2,3,False,False,False,True,True,False,0.983086,0.283787,381.733234,...,[],[],"[54.872093023255815, 56.3, 54.209944751381215,...","[73.95348837209302, 80.4578947368421, 65.19889...","[129.0, 95.0, 181.0, 109.0, 111.0, 109.0, 102....",-6,0,np,North,167.50
3,4,False,False,False,False,True,False,0.836798,0.765713,136.859155,...,[],[],"[56.192, 56.226190476190474, 56.33471074380165...","[-167.872, -167.96428571428572, -168.082644628...","[125.0, 126.0, 121.0, 119.0, 115.0, 112.0, 97....",-6,0,np,North,35.25
4,5,False,False,False,False,True,False,0.720240,0.739238,114.203390,...,[],[],"[51.55172413793103, 51.59130434782609, 51.5882...","[162.77155172413794, 162.81304347826088, 158.2...","[116.0, 115.0, 85.0, 86.0, 88.0, 112.0, 57.0, ...",-6,0,np,North,29.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27840,2033,False,False,False,False,False,True,0.000000,1.000000,1.400000,...,[],[],"[50.0, 50.0, 50.0, 49.25, 48.5]","[-56.5, -56.5, -55.75, -55.0, -55.0]","[1.0, 1.0, 2.0, 2.0, 1.0]",-36,-30,np,North,1.00
27841,2034,False,False,False,False,False,True,0.000000,1.000000,2.400000,...,[],[],"[38.0, 38.0, 38.0, 37.625, 37.625]","[150.5, 150.5, 149.75, 150.875, 150.875]","[1.0, 1.0, 2.0, 4.0, 4.0]",-36,-30,np,North,1.00
27842,2035,False,False,False,False,False,True,0.000000,1.000000,1.400000,...,[],[],"[-43.0, -43.0, -43.0, -43.0, -43.0]","[30.5, 30.5, 31.25, 31.25, 32.0]","[1.0, 1.0, 2.0, 2.0, 1.0]",-36,-30,np,North,1.00
27843,2036,False,False,False,False,False,True,0.000000,1.000000,1.500000,...,[],[],"[-38.5, -38.5, -39.5, -40.0]","[-32.5, -32.5, -33.0, -34.0]","[1.0, 1.0, 3.0, 1.0]",-36,-30,np,North,0.75
27844,2037,False,False,False,False,False,True,0.000000,1.000000,1.000000,...,[],[],"[42.5, 42.5, 42.5, 42.5]","[-170.5, -170.5, -170.5, -170.5]","[1.0, 1.0, 1.0, 1.0]",-36,-30,np,North,0.75

In [2]:
pd.read_parquet('/wolke_scratch/dnikolo/ICON_Data/Postproc_out/Results/R_Agg_30_glaciations_20080901.0015_20080907.2345.parquet')

,Cloud_ID,Time [m],Magnitude,Glac_start_ind,Glac_peak_ind,Linear,line_rmse,Rate_arr,Mean_glac_rate,Glaciation time [h],...,ctt_hist,ctt_std_hist,lat_hist,lon_hist,size_hist_km,min_temp,max_temp,pole,Hemisphere,Lifetime [h]
0,3,300,0.418465,77,97,True,0.028887,"[0.08369301539924594, 0.08369301539924594, 0.0...",0.083693,5.00,...,[],[],"[56.192, 56.226190476190474, 56.33471074380165...","[-167.872, -167.96428571428572, -168.082644628...","[125.0, 126.0, 121.0, 119.0, 115.0, 112.0, 97....",-6,0,np,North,35.25
1,4,1005,0.459478,35,102,True,0.069682,"[0.027431512203069025, 0.027431512203069025, 0...",0.027432,16.75,...,[],[],"[51.55172413793103, 51.59130434782609, 51.5882...","[162.77155172413794, 162.81304347826088, 158.2...","[116.0, 115.0, 85.0, 86.0, 88.0, 112.0, 57.0, ...",-6,0,np,North,29.25
2,5,405,0.981955,59,86,False,0.234942,"[0.024078642275848165, 0.037824598471421576, 0...",0.197166,6.75,...,[],[],"[56.02142857142857, 56.0, 52.56578947368421, 5...","[-29.22142857142857, -29.098591549295776, -23....","[70.0, 71.0, 38.0, 38.0, 36.0, 37.0, 37.0, 42....",-6,0,np,North,22.75
3,7,1155,0.602699,99,176,False,0.160004,"[0.010701425952104104, 0.011641196375133882, 0...",0.057649,19.25,...,[],[],"[47.138888888888886, 47.160714285714285, 47.04...","[-55.5, -55.294642857142854, -56.6590909090909...","[54.0, 56.0, 66.0, 44.0, 44.0, 44.0, 42.0, 43....",-6,0,np,North,44.00
4,9,435,0.456325,1,30,True,0.073337,"[0.06294131501155238, 0.06294131501155238, 0.0...",0.062941,7.25,...,[],[],"[-44.794117647058826, -43.47826086956522, -45....","[152.05882352941177, 149.3913043478261, 152.49...","[51.0, 69.0, 52.0, 51.0, 49.0, 53.0, 55.0, 55....",-6,0,np,North,85.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4010,27766,120,0.579895,1,9,False,0.178405,"[0.24616057444542908, 0.24616057444542908, 0.2...",0.337138,2.00,...,[],[],"[-73.0, -73.0, -73.0, -73.0, -73.0, -73.0, -73...","[-175.0, -175.0, -175.0, -175.0, -175.0, -175....","[3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 4.0, 4.0, ...",-36,-30,np,North,7.75
4011,27774,45,0.566253,0,3,False,0.199375,"[0.22314879691586934, 0.22314879691586934, 1.2...",0.755004,0.75,...,[],[],"[-77.0, -76.6, -76.81818181818181, -76.0]","[-170.75, -169.9, -170.22727272727272, -169.75]","[6.0, 10.0, 11.0, 2.0]",-36,-30,np,North,0.75
4012,27779,15,0.901674,3,4,True,0.000000,[3.6066959971661943],3.606696,0.25,...,[],[],"[-76.0, -76.0, -76.0, -76.0, -76.0]","[-58.0, -58.0, -58.0, -58.0, -58.0]","[3.0, 1.0, 1.0, 1.0, 1.0]",-36,-30,np,North,1.00
4013,27799,285,1.000000,1,20,False,0.217370,"[0.036929350677473285, 0.036929350677473285, 0...",0.295648,4.75,...,[],[],"[-67.0, -67.0, -67.0, -67.0, -67.0, -67.0, -67...","[100.25, 100.25, 99.5, 99.5, 99.5, 99.5, 99.5,...","[2.0, 2.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 5.0, ...",-36,-30,np,North,5.00
4014,27829,105,0.496686,0,7,False,0.238745,"[1.3600956257628944, 1.3600956257628944]",1.360096,1.75,...,[],[],"[-56.5, -57.142857142857146, -57.1428571428571...","[15.5, 13.571428571428571, 13.571428571428571,...","[1.0, 7.0, 7.0, 6.0, 6.0, 6.0, 7.0, 10.0]",-36,-30,np,North,1.75